# Generated by Django 3.2.12 on 2023-01-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='Discound_percentage',
        ),
    ]
