# Generated by Django 3.2.12 on 2023-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_remove_packages_discound_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('Designation', models.CharField(max_length=100)),
            ],
        ),
    ]
