# Generated by Django 3.2.12 on 2023-01-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Hotel_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='Number_of_activities',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='Number_of_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='Number_of_nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='flight_ticket',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='guided_visit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
