# Generated by Django 3.2.12 on 2023-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20230110_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Arrival',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='Departure',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
