# Generated by Django 3.2.12 on 2023-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package/%D/%M/%Y')),
                ('Date', models.DateField()),
                ('package_name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=100)),
                ('package_desc', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
